version: 2

project_name: anarchy-pulse

before:
  hooks:
    - go mod tidy
    - go generate -run fetchsmartctl ./agent

builds:
  - id: anarchy-pulse
    binary: anarchy-pulse
    main: internal/cmd/hub/hub.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: arm

  - id: anarchy-pulse-agent
    binary: anarchy-pulse-agent
    main: internal/cmd/agent/agent.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
      - openbsd
      - windows
    goarch:
      - amd64
      - arm64
      - arm
      - mips64
      - riscv64
      - mipsle
      - mips
      - ppc64le
    gomips:
      - hardfloat
      - softfloat
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: openbsd
        goarch: arm
      - goos: linux
        goarch: mips64
        gomips: softfloat
      - goos: linux
        goarch: mipsle
        gomips: hardfloat
      - goos: linux
        goarch: mips
        gomips: hardfloat
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: riscv64
      - goos: windows
        goarch: riscv64

  - id: anarchy-pulse-agent-linux-amd64-glibc
    binary: anarchy-pulse-agent
    main: internal/cmd/agent/agent.go
    env:
      - CGO_ENABLED=0
    flags:
      - -tags=glibc
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: anarchy-pulse-agent
    formats: [tar.gz]
    ids:
      - anarchy-pulse-agent
    name_template: >-
      {{ .Binary }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]

  - id: anarchy-pulse-agent-linux-amd64-glibc
    formats: [tar.gz]
    ids:
      - anarchy-pulse-agent-linux-amd64-glibc
    name_template: >-
      {{ .Binary }}_
      {{- .Os }}_
      {{- .Arch }}_glibc

  - id: anarchy-pulse
    formats: [tar.gz]
    ids:
      - anarchy-pulse
    name_template: >-
      {{ .Binary }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]

nfpms:
  - id: anarchy-pulse-agent
    package_name: anarchy-pulse-agent
    description: |-
      Agent for Anarchy Pulse
      Anarchy Pulse is a lightweight server monitoring platform that includes Docker
      statistics, historical data, and alert functions. It has a friendly web
      interface, simple configuration, and is ready to use out of the box.
      It supports automatic backup, multi-user, OAuth authentication, and
      API access.
    maintainer: henrygd <hank@henrygd.me>
    section: net
    ids:
      - anarchy-pulse-agent
    formats:
      - deb
    contents:
      - src: ./supplemental/debian/anarchy-pulse-agent.service
        dst: lib/systemd/system/anarchy-pulse-agent.service
        packager: deb
      - src: ./supplemental/debian/copyright
        dst: usr/share/doc/anarchy-pulse-agent/copyright
        packager: deb
      - src: ./supplemental/debian/lintian-overrides
        dst: usr/share/lintian/overrides/anarchy-pulse-agent
        packager: deb
    scripts:
      postinstall: ./supplemental/debian/postinstall.sh
      preremove: ./supplemental/debian/prerm.sh
      postremove: ./supplemental/debian/postrm.sh
    deb:
      predepends:
        - adduser
        - debconf
      scripts:
        templates: ./supplemental/debian/templates
        config: ./supplemental/debian/config.sh

scoops:
  - ids: [anarchy-pulse-agent]
    name: anarchy-pulse-agent
    repository:
      owner: henrygd
      name: anarchy-pulse-scoops
    homepage: "https://github.com/CarShyne/beszel.Ana"
    description: "Agent for Anarchy Pulse, a lightweight server monitoring platform."
    license: MIT
    skip_upload: '{{ if eq (tolower .Env.IS_FORK) "true" }}true{{ else }}auto{{ end }}'

# # Needs choco installed, so doesn't build on linux / default gh workflow :(
# chocolateys:
#   - title: Anarchy Pulse Agent
#     ids: [anarchy-pulse-agent]
#     package_source_url: https://github.com/jt7777/anarchy-pulse-chocolatey
#     owners: henrygd
#     authors: henrygd
#     summary: 'Agent for Anarchy Pulse, a lightweight server monitoring platform.'
#     description: |
#       Anarchy Pulse is a lightweight server monitoring platform that includes Docker statistics, historical data, and alert functions.

#       It has a friendly web interface, simple configuration, and is ready to use out of the box. It supports automatic backup, multi-user, OAuth authentication, and API access.
#     license_url: https://github.com/jt7777/anarchy-pulse/blob/main/LICENSE
#     project_url: https://github.com/CarShyne/beszel.Ana
#     project_source_url: https://github.com/CarShyne/beszel.Ana
#     docs_url: https://github.com/CarShyne/beszel.Ana/getting-started
#     icon_url: https://cdn.jsdelivr.net/gh/selfhst/icons/png/anarchy-pulse.png
#     bug_tracker_url: https://github.com/CarShyne/beszel.Ana/issues
#     copyright: 2025 henrygd
#     tags: foss cross-platform admin monitoring
#     require_license_acceptance: false
#     release_notes: 'https://github.com/CarShyne/beszel.Ana/releases/tag/v{{ .Version }}'

brews:
  - ids: [anarchy-pulse-agent]
    name: anarchy-pulse-agent
    repository:
      owner: henrygd
      name: homebrew-anarchy-pulse
    homepage: "https://github.com/CarShyne/beszel.Ana"
    description: "Agent for Anarchy Pulse, a lightweight server monitoring platform."
    license: MIT
    skip_upload: '{{ if eq (tolower .Env.IS_FORK) "true" }}true{{ else }}auto{{ end }}'
    extra_install: |
      (bin/"anarchy-pulse-agent-launcher").write <<~EOS
        #!/bin/bash
        set -a
        if [ -f "$HOME/.config/anarchy-pulse/anarchy-pulse-agent.env" ]; then
          source "$HOME/.config/anarchy-pulse/anarchy-pulse-agent.env"
        fi
        set +a
        exec #{bin}/anarchy-pulse-agent "$@"
      EOS
      (bin/"anarchy-pulse-agent-launcher").chmod 0755
    service: |
      run ["#{bin}/anarchy-pulse-agent-launcher"]
      log_path "#{Dir.home}/.cache/anarchy-pulse/anarchy-pulse-agent.log"
      error_log_path "#{Dir.home}/.cache/anarchy-pulse/anarchy-pulse-agent.log"
      keep_alive true
      restart_delay 5
      process_type :background

winget:
  - ids: [anarchy-pulse-agent]
    name: anarchy-pulse-agent
    package_identifier: henrygd.anarchy-pulse-agent
    publisher: henrygd
    license: MIT
    license_url: "https://github.com/CarShyne/beszel.Ana/blob/main/LICENSE"
    copyright: "2025 henrygd"
    homepage: "https://github.com/CarShyne/beszel.Ana"
    release_notes_url: "https://github.com/CarShyne/beszel.Ana/releases/tag/v{{ .Version }}"
    publisher_support_url: "https://github.com/CarShyne/beszel.Ana/issues"
    short_description: "Agent for Anarchy Pulse, a lightweight server monitoring platform."
    skip_upload: '{{ if eq (tolower .Env.IS_FORK) "true" }}true{{ else }}auto{{ end }}'
    description: |
      Anarchy Pulse is a lightweight server monitoring platform that includes Docker
      statistics, historical data, and alert functions. It has a friendly web
      interface, simple configuration, and is ready to use out of the box.
      It supports automatic backup, multi-user, OAuth authentication, and
      API access.
    tags:
      - homelab
      - monitoring
      - self-hosted
    repository:
      owner: henrygd
      name: anarchy-pulse-winget
      branch: henrygd.anarchy-pulse-agent-{{ .Version }}
      token: "{{ .Env.WINGET_TOKEN }}"
      # pull_request:
      #   enabled: true
      #   draft: false
      #   base:
      #     owner: microsoft
      #     name: winget-pkgs
      #     branch: master

release:
  draft: true

changelog:
  disable: true
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
