# Docs: https://github.com/CarShyne/beszel.Ana/getting-started
# Env vars: https://github.com/CarShyne/beszel.Ana/environment-variables

services:
  anarchy-pulse:
    image: jt7777/anarchy-pulse:latest
    container_name: anarchy-pulse
    restart: unless-stopped
    environment:
      APP_URL: http://localhost:8090
    ports:
      - 8090:8090
    volumes:
      - ./anarchy_pulse_data:/anarchy_pulse_data
      - ./anarchy_pulse_socket:/anarchy_pulse_socket
    # healthcheck:
    #   test: ['CMD', '/anarchy-pulse', 'health', '--url', 'http://localhost:8090']
    #   interval: 120s
    #   start_period: 10s
    #   timeout: 5s

  anarchy-pulse-agent:
    image: jt7777/anarchy-pulse-agent:latest
    container_name: anarchy-pulse-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./anarchy_pulse_agent_data:/var/lib/anarchy-pulse-agent
      - ./anarchy_pulse_socket:/anarchy_pulse_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /anarchy_pulse_socket/anarchy-pulse.sock
      HUB_URL: http://localhost:8090
      TOKEN: <token>
      KEY: "<key>"
    # healthcheck:
    #   test: ['CMD', '/agent', 'health']
    #   interval: 120s
