# Docs: https://github.com/CarShyne/beszel.Ana/hub-installation
# Env vars: https://github.com/CarShyne/beszel.Ana/environment-variables

services:
  anarchy-pulse:
    image: "jt7777/anarchy-pulse"
    container_name: "anarchy-pulse"
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./anarchy_pulse_data:/anarchy_pulse_data
    # healthcheck:
    #   test: ['CMD', '/anarchy-pulse', 'health', '--url', 'http://localhost:8090']
    #   interval: 120s
    #   start_period: 10s
    #   timeout: 5s
